Add controllers
Piroggard/java-shareit pull request #1
Opened 2023-10-08 18:07 UTC by Piroggard

2023-10-09 19:24 UTC, sergeymamonov requested changes
Класс Booking потребуется в следующих спринтах.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    int id;
Пропущены модификаторы доступа.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationData.java
> +public class ValidationData extends RuntimeException {
Где используется это исключение?

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +public class ValidationExceptionResponse {
Это класс обработчик (Handler) возникающих ошибок, а не ответ (Response).

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +
Лишние пустые строки.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationId.java
> +public class ValidationId extends RuntimeException {
Исключение должно содержать в себе слово Exception. И лучше, чтобы оно было заключительным словом в названии.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
При возникновении этого исключения throw new ValidationId("Невозможно обновитть данные") клиенту вернется 404 статус, что неверно, должен быть 400 статус.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +}
Лучше еще сделать обработку RuntimeException.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +            itemList.add(item);
addAll()

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    int id;
Модификаторы доступа пропущены.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    int id;
Пропущены модификаторы доступа. Плюс лучше добавить модификатор final к полям и классу.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Все ли нужны аннотации из тех, что входят в аннотацию @Data? Лучше выбрать только те, которые нужны, и указать именно их.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    int id;
Модификаторы доступа.

2023-10-09 19:24 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +            if (c == '@') {
А если будет введены такие варианты?
А@@mail, 
@mail, 
mail@, 
@

Как вариант посмотреть уже готовые реализации валиадации почты, например с помощью аннотаций.

2023-10-10 18:10 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    int id;
Исправлено.

2023-10-10 18:10 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/ValidationData.java
> +public class ValidationData extends RuntimeException {
В ItemValidation и в UserValidation. Исключения возникают когда получаем не все данные в объекте.

2023-10-10 18:10 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +public class ValidationExceptionResponse {
Исправлено.

2023-10-10 18:10 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +
Исправлено.

2023-10-10 18:12 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/ValidationId.java
> +public class ValidationId extends RuntimeException {
Исправлено.

2023-10-10 18:12 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    int id;
Исправлено.

2023-10-10 18:13 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    int id;
Исправлено.

2023-10-10 18:16 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Исправлено.

2023-10-10 18:16 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    int id;
Исправлено.

2023-10-10 18:16 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +            if (c == '@') {
Исправлено.

2023-10-10 19:13 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +            if (c == '@') {
Но я не уверен что правильно, так как захаркодил текст при появлении исключения MethodArgumentNotValidException.

2023-10-11 17:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationData.java
> +public class ValidationData extends RuntimeException {
Класс исключения должен оканчиваться на Exception

2023-10-11 17:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionsHandler.java
> +public class ValidationExceptionsHandler {
Здесь слово Validation в названии не очень подходит.

2023-10-11 17:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Не исправлено.

2023-10-11 17:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionResponse.java
> +}
Не исправлено.

2023-10-11 17:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Посмотреть по всему проекту, где используется эта аннотация.

2023-10-11 17:35 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +            if (c == '@') {
Текст можно и так оставить, здесь это не кретично.

2023-10-11 17:37 UTC, sergeymamonov approved these changes

2023-10-11 17:37 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionsHandler.java
> +}
У вас еще есть исключение DataNotFoundException.

2023-10-13 10:55 UTC, merged