Add bookings
Piroggard/java-shareit pull request #2
Opened 2023-10-30 14:27 UTC by Piroggard

2023-10-31 04:12 UTC, sergeymamonov requested changes
DataNotFoundException исключение нигде не используется. И отсутствие какой-либо сущности не нужно наследовать от NPE. У них разный смысл. NPE, это непроверяемое исключение, когда возникла ситуация, что в коде что-то ожидается, то пришел null. DataNotFoundException - понимается, что выполнена какая-то проверка и объект не найден, например, пользователь в БД.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Dto это неизменяемый класс, поэтому можно добавить модификатор final к определению класса и полям. А также отказаться от аннотации @Setter, так как это модифицирующий метод.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +import lombok.*;
Лучше не использовать импорт через *, так как это может приводить к конфликтам импорта из разных пакетов. Если это выполняется автоматически идеей, то лучше отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServise.java
> +    Booking addBooking(BookingDto bookingDto, Integer booker) throws ItemAvailableException;
Не нужно прокидывать исключение вверх до контроллера и выше. Нужно унаследовать это и другие исключения от непроверяемой ошибки, например RuntimeException.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +                    System.out.println(1);
System.out.println в коде быть не должно. Нужно удалить по всему проекту.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    JpaBooking jpaBooking;
У полей отсутствуют модификаторы доступа.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +        User user = userStorage.getUser(booking.getBooker().getId());
Так с БД не работают. Если вам нужно получить из БД связанные сущности, как например бронирование и пользователь, то лучше сделать запрос с джоином. Плюс метод save возвращает записываемую сущность.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Booking addBooking(@Validated @RequestHeader("X-Sharer-User-Id") Integer booker, @RequestBody BookingDto bookingDto) throws ItemAvailableException {
Старайтесь не выходить за лимит в 120 символов.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/StatusException.java
> +public class StatusException extends Exception {
Унаследоваться от непроверяемого исключения.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionsHandler.java
>      public Map<String, String> validationData(final ValidationException e) {
Три подряд метода с ошибками, названия которые не несут емкой информации, чтобы понять, что за ошибка, к чему она ведет и почему возникла. То есть по названию ValidationException не связать с CONFLICT, ValidationData с BAD_REQUEST и так далее. Название класса ошибки должно быть информативным.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        CommentDto commentDto1 = CommentDto.builder()
Можно сразу вернуть без создания commentDto1.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Comment comment1 = jpaCommentRepository.save(comment);
Лучше на используйте такой прием, называть объекты comment**1**.  Как понять, чем comment отличается от comment**1**?

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          for (Item item : itemStorage.getItems()) {
Вам нужно получить из БД несколько объект, но для этого вы выгружаете из БД все объекты (а это могут быть миллионы). Фильтрацию нужно делать на стороне БД.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDtoResponse getItem(Integer itemId, Integer id) {
Глядя на метод непонятно, что он возвращает. getItem - подразумевает, что возвращается один объект. 

return itemList - подразумевается, что список объектов.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    JpaItemRepository jpaItemRepository;
Проверьте по всему проекту модификаторы доступа у полей.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +            CommentDto commentDto = CommentDto.builder()
Лучше создавать отдельные классы конвертеры для конвертации из одного класса в другой.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsAfterOrStartEqualsOrderByStart(item.getId(),
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsBeforeOrStartEqualsOrderByEndDesc(item.getId(),
Аналогично.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
>      UserStorage userStorage;
Валидатор не может обращаться к БД. Валидатор только валидирует переданные ему данные. Запросы к слою хранения данных делаются из сервиса.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void validationUser(UserDto user, Integer id) throws ValidationException {
Что это за неинформативный параметр Integer id, плюс который не используется в методе.

2023-10-31 04:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void validationEmailUpdate(UserDto userDto, Integer id) {
Здесь id - это айдишник чего? Нужно дать информативное название параметру.

2023-10-31 14:11 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServise.java
> +    Booking addBooking(BookingDto bookingDto, Integer booker) throws ItemAvailableException;
Исправлено

2023-10-31 14:12 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +    JpaBooking jpaBooking;
Исправлено

2023-10-31 16:36 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +        User user = userStorage.getUser(booking.getBooker().getId());
Исправлено

2023-10-31 16:39 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +        User user = userStorage.getUser(booking.getBooker().getId());
Исправлено

2023-10-31 16:40 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Booking addBooking(@Validated @RequestHeader("X-Sharer-User-Id") Integer booker, @RequestBody BookingDto bookingDto) throws ItemAvailableException {
Исправлено

2023-10-31 16:40 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/StatusException.java
> +public class StatusException extends Exception {
Исправлено

2023-10-31 17:28 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          for (Item item : itemStorage.getItems()) {
Исправлено

2023-10-31 17:31 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Исправлено

2023-10-31 17:32 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +import lombok.*;
Исправлено

2023-10-31 17:33 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +import lombok.*;
Идея сама подставляет *

2023-10-31 17:35 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +                    System.out.println(1);
Исправлено

2023-10-31 18:02 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        CommentDto commentDto1 = CommentDto.builder()
Если вернуть сразу Comment я не пройду тесты, так как ожидается в место объектов id

2023-10-31 18:04 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public ItemDtoResponse getItem(Integer itemId, Integer id) {
Исправлено

2023-10-31 18:43 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsAfterOrStartEqualsOrderByStart(item.getId(),
Проблема в том что мы отдельно не храним последнее и будущее бронирование, его нужно получить и замапить в другой объект и вернуть с Item. К сожалению. я не нашел как правильно собрать другой объект через запрос, в теории к курсу такой информации тоже не было.

2023-10-31 20:23 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/validation/ItemValidation.java
>      UserStorage userStorage;
Исправлено

2023-10-31 20:23 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void validationUser(UserDto user, Integer id) throws ValidationException {
Исправлено

2023-10-31 20:33 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionsHandler.java
>      public Map<String, String> validationData(final ValidationException e) {
Исправлено

2023-10-31 20:48 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +            CommentDto commentDto = CommentDto.builder()
Исправлено

2023-11-01 20:31 UTC, sergeymamonov commented
Исключение DataNotFoundException нигде не используется и его нужно поэтому удалить.

2023-11-01 20:32 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Не исправлено, так как это относится ко всем классам dto в проекте. Пример, ItemDto.

2023-11-01 20:32 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +import lombok.*;
Если это выполняется автоматически идеей, то лучше отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2023-11-01 20:34 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServise.java
> +    Booking addBooking(BookingDto bookingDto, Integer booker) throws ItemAvailableException;
Не исправлено, так как в этом интерфейсе нигде не должно быть throws ...Exception.

2023-11-01 20:35 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +                    System.out.println(1);
Проверьте в классе UserValidation. Используйте поиск по проекту Ctrl + Shift + F.

2023-11-01 20:37 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    JpaItemRepository jpaItemRepository;
Не исправлено, пример ItemStorage.

2023-11-01 20:42 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exception/ValidationExceptionsHandler.java
>      public Map<String, String> validationData(final ValidationException e) {
Нужно было изменить названия классов исключений.

2023-11-01 20:43 UTC, sergeymamonov commented
Общепринято, что все классы исключений завершаются на ...Exception. Обратите внимание на класс ValidationData, он не соответствует этой моделе.

2023-11-01 20:48 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        CommentDto commentDto1 = CommentDto.builder()
return CommentDto.builder

...

.build()

2023-11-01 20:54 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsAfterOrStartEqualsOrderByStart(item.getId(),
В работе разработчика скорее всего вы постоянно будете работать с базой данных, поэтому без освоения этого материала дальше будет сложно проходить курс. В данном случае можно выгрузить бронирования, которые относятся к нужным вещам и в этих бронирования для каждой вещи найти nextBooking и lastBooking. В случае возникновения вопросов обращайтесь за консультацией к наставнику.

2023-11-02 18:23 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsAfterOrStartEqualsOrderByStart(item.getId(),
Исправлено

2023-11-02 18:23 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +                    .findFirstByItemIdAndStatusAndStartIsBeforeOrStartEqualsOrderByEndDesc(item.getId(),
Исправлено

2023-11-02 18:28 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/validation/UserValidation.java
> +    public void validationEmailUpdate(UserDto userDto, Integer id) {
Исправлено

2023-11-02 19:00 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    JpaItemRepository jpaItemRepository;
Исправлено

2023-11-02 19:44 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +                    System.out.println(1);
Спасибо, исправлено!

2023-11-02 19:49 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Исправлено

2023-11-02 19:49 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  public class BookingDto {
Исправлено

2023-11-04 10:18 UTC, kesch9 reviewed
Требуется доработка

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    email VARCHAR(255)
name и email надо пометить not null, а для email  еще добавить unique, т.к. еmail уникальный

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    id INT AUTO_INCREMENT PRIMARY KEY,
id лучше использовать тип BIGINT

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    request VARCHAR(255)
owner и request это FK на user и на request надо сразу написать
  owner_id BIGINT NOT NULL,
  request_id BIGINT,
  CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (user_id),
  CONSTRAINT FK_ITEM_ON_REQUEST FOREIGN KEY (request_id) REFERENCES item_requests (item_request_id),
и добавьте таблицу request
CREATE TABLE IF NOT EXISTS item_requests (
  item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(4000) NOT NULL,
  requester_id BIGINT,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_item_request PRIMARY KEY (item_request_id),
  CONSTRAINT FK_ITEM_REQUEST_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (user_id)
);

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    end_of_booking TIMESTAMP,
start_of_booking, end_of_booking имеют тип TIMESTAMP WITHOUT TIME ZONE, т.к. в java вы используете Localdatetime, а это соответствует этому типу, также их надо пометить not null

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    status VARCHAR(255),
статус not null

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/schema.sql
> +    created TIMESTAMP,
created имеет тип
TIMESTAMP WITHOUT TIME ZONE NOT NULL

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>      private int id;
лучше для id использовать BIGINT. а в java это LONG

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "start_of_booking")
В Column надо добавить еще  nullable = false, где поле не может быть null

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @NonNull
Здесь nonnull, а в моделях и в БД не пометили, это надо подправить

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +public class BookingConcise {
BookingConcise это все таки dto а не модель

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                           @RequestParam(name = "state", required = false) String state) {
Поставьте defaultValue = "all" тогда вам не надо, будет проверку на null и делать два метода

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            return bookingServise.getBookingByState(state, id);
Не нужно делать два метода, делаем один, добавляем defaultValue и будет искать как all

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +public class BookingStorage {
BookingStorage не нужен больше, вам spring-data сформирует имплементацию репозитория по интерфейсу теперь работаем через него

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/storage/JpaBooking.java
> +public interface JpaBooking extends JpaRepository<Booking, Integer> {
Не надо писать Jpa можно просто BookingRepository

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/storage/JpaBooking.java
> +    List<Booking> findBookingByItem_OwnerOrderByStartDesc(Integer idOwner);
Писать явно указание способа сортировки не нужно, а если нужно будет по другому написать, нужно будет писать новый метод, используем org.springframework.data.domain.Sort
вот так его формируем
Sort newestFirst = Sort.by(Sort.Direction.DESC, "start");
а потом просто передаем в метод
List<Booking> findByItem_Owner_Id(Long ownerId, Sort sort);
Также и для query можно передать Sort
	@Query(" select b " +
			"from Booking b " +
			"where b.booker.id = ?1 " +
			"  and b.status = 'WAITING'")
	List<Booking> findPending(Long bookerId, Sort sort);

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +    public List<Booking> getBookingByState(String state, Integer id) {
state это явно enum, добавляем его, а затем парсим строку, если отпарсить не получается отправляем ошибку

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +        if (state == null) {
Null это all

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(name = "name")
Во всех моделях надо добавить в настройки полей 
nullable = false, length = ...
согласно БД

2023-11-04 10:18 UTC, kesch9 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private UserStorage userStorage;
В остальных сервисах аналогичные ошибки как и в booking, работаем через JpaRepository и добавляем Sort где нужно

2023-11-04 10:18 UTC, kesch9 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:./db/java-shareit
Надо было оставить
jdbc:h2:mem:shareit

2023-11-04 10:49 UTC, Piroggard commented on src/main/resources/schema.sql
> +    email VARCHAR(255)
Исправлено

2023-11-04 10:50 UTC, Piroggard commented on src/main/resources/schema.sql
> +    id INT AUTO_INCREMENT PRIMARY KEY,
Исправлено

2023-11-04 11:04 UTC, Piroggard commented on src/main/resources/schema.sql
> +    end_of_booking TIMESTAMP,
Исправлено

2023-11-04 11:06 UTC, Piroggard commented on src/main/resources/schema.sql
> +    status VARCHAR(255),
Исправлено

2023-11-04 11:08 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>      private int id;
Исправлено

2023-11-04 11:15 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @NonNull
Исправлено

2023-11-04 11:17 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/BookingConcise.java
> +public class BookingConcise {
Исправлено

2023-11-04 11:29 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                           @RequestParam(name = "state", required = false) String state) {
Исправлено

2023-11-04 12:00 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            return bookingServise.getBookingByState(state, id);
Исправлено

2023-11-04 13:09 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +public class BookingStorage {
Исправлено во всех классах

2023-11-04 13:12 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/storage/JpaBooking.java
> +public interface JpaBooking extends JpaRepository<Booking, Integer> {
Исправлено

2023-11-04 13:56 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +    public List<Booking> getBookingByState(String state, Integer id) {
исправлено

2023-11-04 14:01 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/servise/BookingServiseImpl.java
> +        if (state == null) {
Исправлено

2023-11-04 14:02 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private UserStorage userStorage;
Исправлено

2023-11-04 14:05 UTC, Piroggard commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:./db/java-shareit
Исправлено

2023-11-04 14:06 UTC, Piroggard commented on src/main/resources/schema.sql
> +    created TIMESTAMP,
Исправлено

2023-11-04 19:05 UTC, kesch9 approved these changes
Approve

2023-11-07 13:56 UTC, merged