Add item requests
Piroggard/java-shareit pull request #3
Opened 2023-11-12 15:03 UTC by Piroggard

2023-11-13 21:38 UTC, sergeymamonov requested changes

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/enums/State.java
> +public enum State {
Этот класс где-то используется?

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +     LocalDateTime start;
Форматирование

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exceptions/ValidationException.java
> +    public static class ErrorResponse {
Зачем этот класс помещен сюда? Класс исключения - это отдельный класс. Класс сообщения об ошибке - это другой класс.

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +     String name;
Форматирование. Проверьте по всему проекту.

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if ((from < 0 || size < 0 || (from == 0 && size == 0))) {
Здесь вы делаете валидацию параметров пагинации. А в классе BookingController вы делаете валидацию с помощью аннотаций. То есть одно и тоже действие в разных классах вы делаете по-разному.

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemsList.forEach(this::addLastAndNextDateTimeForBookingToItem);
Здесь выполняются запросы к БД в цикле.

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +@Setter
Сеттера здесь быть не может.

2023-11-13 21:38 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public Collection<UserDto> getAllUsers() {
Collection - это слишком общий интерфейс. То есть тут может вернуться и множество, и массив и так далее.

2023-11-13 21:38 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/storage/BookingRepositoryTest.java
> +import org.junit.jupiter.api.*;
Лучше не использовать импорт через .*

2023-11-13 21:38 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        //Booking booking = mapper.map(bookingDto, Booking.class);
В проекте не должно быть закомментированного кода.

2023-11-13 21:38 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void getAllForBookerREJECTEDTest() {
camelCase

2023-11-14 16:46 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/enums/State.java
> +public enum State {
Да, это статусы вещей бронирования, используется в сервисе

2023-11-14 16:46 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +     LocalDateTime start;
Исправлено

2023-11-14 16:48 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/exceptions/ValidationException.java
> +    public static class ErrorResponse {
Перенес в shareit

2023-11-14 16:53 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if ((from < 0 || size < 0 || (from == 0 && size == 0))) {
Исправлено

2023-11-14 16:54 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemsList.forEach(this::addLastAndNextDateTimeForBookingToItem);
Исправлено

2023-11-14 16:54 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +@Setter
Исправлено

2023-11-14 16:56 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public Collection<UserDto> getAllUsers() {
Исправлено

2023-11-14 16:58 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/booking/enums/State.java
> +public enum State {
Попутал с статусом, удалил не нужный класс

2023-11-14 18:32 UTC, Piroggard commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    void getAllForBookerREJECTEDTest() {
Исправлено

2023-11-14 18:33 UTC, Piroggard commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +        //Booking booking = mapper.map(bookingDto, Booking.class);
Исправлено

2023-11-14 18:34 UTC, Piroggard commented on src/test/java/ru/practicum/shareit/booking/storage/BookingRepositoryTest.java
> +import org.junit.jupiter.api.*;
Исправлено

2023-11-14 18:34 UTC, Piroggard commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +     String name;
Исправлено

2023-11-15 03:45 UTC, sergeymamonov approved these changes

2023-11-15 03:45 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/exceptions/ValidationExceptionsHandler.java
> +    public ValidationException.ErrorResponse handleConflictException(final ConflictException e) {
Посмотрите здесь вложенный класс ValidationException.ErrorResponse. Сделайте просто 

public ErrorResponse ...

Не нужно его никуда вкладывать.

2023-11-15 03:45 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
Здесь будет деление на ноль, потому что в ItemController в методе getItemsByUser нет валидации аннотациями входящих параметров пагинации. Посмотрите как вы сделали BookingController.

2023-11-15 03:45 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> allBookings = bookingRepository.findAll();
Бронирований в БД может быть много миллионов. Все они нам не нужны. Можно взять из БД только те, которые нам нужны, которые относятся к списку itemList, то есть бронирования, у которых itemId in itemList.

2023-11-15 03:45 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Collection<ItemDto> searchItem(@RequestParam @NotBlank String text,
Посмотрите поиском по всему проекту, где вы еще используете интерфейс Collection. И лучше поменять на более конкретный интерфейс.

2023-11-19 17:18 UTC, merged