ТЗ 16
Piroggard/java-shareit pull request #4
Opened 2023-11-19 17:52 UTC by Piroggard

2023-11-21 05:51 UTC, sergeymamonov requested changes
Из проекта необходимо убрать все TODO.

2023-11-21 05:51 UTC, sergeymamonov commented on pom.xml
>  	<dependencies>
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию.

2023-11-21 05:51 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  @Data
С помощью этой аннотации можно менять неизменяемый объект dto.

2023-11-21 05:51 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/UnsupportedStateException.java
> +public class UnsupportedStateException extends RuntimeException {
Исключение нигде не используется.

2023-11-21 05:51 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                                 @Min(value = 0, message = "Size must be more than 0")
Размер страницы не должен равняться 0. А аннотация min - это не строгое равенство. https://docs.oracle.com/javaee%2F6%2Fapi%2F%2F/javax/validation/constraints/Min.html

The annotated element must be a number whose value must be higher **or equal** to the specified minimum.

2023-11-21 05:51 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/util/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Конструктор и геттеры можно не писать руками, а воспользоваться аннотациями Ломбок.

2023-11-21 05:51 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new MethodArgumentNotValidException(HttpStatus.BAD_REQUEST, "Неправильный параметр пагинации");
В сервис валидации.

2023-11-21 05:51 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          if (commentDto.getText().isEmpty()) {
В сервис валидации. Проверить весь сервис на предмет проверок, которые можно перенести в сервис валидации.

2023-11-24 15:11 UTC, Piroggard commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>  @Data
Исправлено

2023-11-24 15:24 UTC, Piroggard commented on gateway/src/main/java/ru/practicum/shareit/exceptions/UnsupportedStateException.java
> +public class UnsupportedStateException extends RuntimeException {
Исправлено

2023-11-24 15:32 UTC, Piroggard commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new MethodArgumentNotValidException(HttpStatus.BAD_REQUEST, "Неправильный параметр пагинации");
Вся валидация происходит в основном классе сервиса

2023-11-24 17:56 UTC, Piroggard commented on gateway/src/main/java/ru/practicum/shareit/util/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Исправлено

2023-11-25 04:56 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Data
Пользуйтесь поиском по проекту (Ctrl + Shift + F), и вы сразу будете видеть, где у вас что в проекте.

2023-11-25 04:56 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                          @Min(value = 0, message = "Parameter 'size' must be " +
Поищите c помощью @Min для параметра size по всему проекту.

2023-11-25 04:56 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new MethodArgumentNotValidException(HttpStatus.BAD_REQUEST, "Неправильный параметр пагинации");
Нет, это неверно. Из задания:

"Можно вынести часть приложения, с которой непосредственно работают пользователи, в отдельное небольшое приложение и назвать его, допустим, **gateway** (англ. «шлюз»). В нём будет выполняться вся валидация запросов — некорректные будут исключаться."

То есть все, что можно проверить без обращения к БД должно валидироваться в сервисе gateway.

2023-11-25 04:56 UTC, sergeymamonov approved these changes

2023-11-25 07:37 UTC, merged